/**
 * DOCUMENT CONTENT OBJECTS
 * @summary This file contains the data objects that form the content of this page
 * @author Cliff Crerar
 * Created at     : 2018-11-15 16:47:36
 * Last modified  : 2018-11-16 11:43:07
 */

const content = {
    /**
     * 1. Introduction
     */
    Introduction: {
        textArr: [
            // Paragraph 1
            'Structured query language (SQL) is a <a id="dsfl">domain-specific language</a> used to program, design and administer <a id="rdbms">relational-database-management systems</a>(RDBMS).',
            // Paragraph 2
            'The language is used by many types of users including software developers, database administrators, consultants implementing external software that must integrate with operational and financial business systems.',
            // Paragraph 3
            'In this tech age there are even users in other functions of business like finance and procurement that prefer to interact directly with their data instead of opting to use a front end application. It can also be a powerful tool in the hands of an internal auditor.',
            // Paragraph 4
            'RDBMS, also known as Relational Databases or DBMS, are the industry standard data repositories used by most business systems, large and small, that must store day to day transactions generated under normal operating conditions. These types of database is also referred to as <a id="oltp">online transaction processing</a> ,or OLTP.',
            // Paragraph 5
            'These OLTP database are optimised to process many single or small batches of transaction, even when the database is distributed across multiple regions or even globally while always maintaining consistency of data.',
            // Paragraph 6
            'The other general type of RDBMS is <a id="olap">on-line analytical processing</a> or OLAP database. This type of database is optimised to process vast amounts of transactions normally generated by an OLTP database, and OLTP is normally the source of an OLAP repository.',
            // Paragraph 7
            'OLAP is mainly for generating information to support management decision making in all business functions and at all levels of management.<br><br>',
            // Paragraph 8
            'There are many variations of RDBMS, open-source and enterprise. Most notable enterprise RDBMS is Oracle database and Microsoft SQL server. PostgreSQL, MySQL and SQLite are most notable open-source RDBMS.',
            // Paragraph 9
            'SQL is a language that is based on <a id="relAlg">relational algebra</a> and <a id="tupCalc">tuple calculus</a>. It consists of a subset of languages and are listed as follows:<br>',
            // Unordered list
            '<ul class="intro-ul">' +
            '<li>Data Query Language (DQL)</li>' +
            '<li>Data Definition Language (DDL)</li>' +
            '<li>Data Manipulation Language (DML)</li>' +
            '<li>Data Transaction Language (DTL)</li>' +
            '<li>Data Control Language (DCL)</li>' +
            '</ul>',
            // Paragraph 10
            '<i>DQL</i> is used for data retrieval used for display in application or in a database client. <i>DDL</i> is used to define the database and is used to implement database objects such as tables, columns, relationships and constraints. <i>DML</i> is used to create data initiated by business transactions as well as updating or deleting data, <i>DML</i> is also used to alter database objects such modifying tables or columns. <i>DTL</i> is used to control the way the database processes transactions and <i>DCL</i> is mostly related to users and access rights.',
            // Paragraph 11
            'SQL can also be described as a <a id="decLang">declarative language</a> (<a id="fourGl">4GL</a>) language and includes some elements of a <a id="procLang">procedural language</a>.',
        ],
        links: {
            dsfl: 'https://en.wikipedia.org/wiki/Domain-specific_language',
            relAlg: 'https://en.wikipedia.org/wiki/Relational_algebra',
            tupCalc: 'https://en.wikipedia.org/wiki/Tuple_relational_calculus',
            rdbms: 'https://en.wikipedia.org/wiki/Relational_database_management_system',
            oltp: 'https://en.wikipedia.org/wiki/Online_transaction_processing',
            olap: 'https://en.wikipedia.org/wiki/Online_analytical_processing',
            decLang: 'https://en.wikipedia.org/wiki/Declarative_programming',
            procLang: 'https://en.wikipedia.org/wiki/Procedural_programming',
            fourGl: 'https://www.techopedia.com/definition/24308/fourth-generation-programming-language-4gl'
        }
    },
    /**
    * 2. About this document
    */
    About_this_document: {
        textArr: [
            'As mentioned in the introduction section; there are many brands of relational database, enterprise and open source. However; as per the document title this document will cover the basics of <a id="t-sql”>Transact Structured Query Language or T-SQL</a>.',

            `<div class="paper question"><b>What is T-SQL</b>${questionSvg}</div>`,

            `T-SQL is Microsoft's implementation of SQL in their proprietary brand of RDBMS called <a id="”>Microsoft SQL Server</a>.`,

            `<div class="paper question"><b>Microsoft SQL Server is a enterprise RDBMS. Is that not overkill for this</b>${questionSvg}</div>`,

            'Indeed way overkill, Microsoft have a scaled down version of the mighty enterprise version specifically for learning T-SQL in a Microsoft environment called Microsoft SQL Server Express, MS SQL Express.',

            'This version may also be used for to implement application that does not require enterprise scaling. The next section <a href="Getting_started" will point you to the resources you need to acquire the software as well as instructions on installation thereof.',

            `<div class="paper question"><b>What are "The Basics"</b>${questionSvg}<div>`,

            'The great thing about SQL is that knowing the basics can go a long way.',

            'For instance, say you are  a data analyst that uses excel to analyse and maintain data. Excel is a great tool and works very well for creating reports, but although it can in theory handle 1 million plus a bit records. Anything above 200 000 and it will just be a frustration to use.',

            'The content of this document will place you in a position to administer data using the power of Microsofts Powerful Database engine without having to acquire an expensive more efficient alternative to Excel.',

            `<div class="paper question"><b>What is covered in this document</b>${questionSvg}</div>`,

            'Even though the basics can take you a long way, the road to learning advanced SQL is even longer as it covers multiple disciplines like distributed database administration, database design and implementation, database security etc.',

            'If you are a software developer, solutions architect or database administrator and you already know some SQL; this document is unfortunately not appropriate for you. Feel free to go to the <a href="#Advanced_topics">Advanced topics</a> section of this page which might guide you toward the appropriate material.',

            'If you are brand new to RDBMS and you wish to get certified, there is a link to the Microsoft Virtual Academy in the <a href="#Additional_resources">Additional resources</a> section of this document.',

            'Here is a list of a few general features that this document will not cover:',

            '<ul>' +
            '<li>Merge</li>' +
            '<li>Unions</li>' +
            '<li>Cursors</li>' +
            '<li>Triggers</li>' +
            '<li>Declaring and using variables</li>' +
            '<li>Stored procedures</li>' +
            '<li>Common table expressions</li>' +
            '<li>Conditional operations (IF, CASE)</li>' +
            '<li>Loops in T-SQL</li>' +
            '<li>Data control language</li>' +
            '</ul>'
        ],
        links: {

        }
    }
}